### ISSUE TITLE
Polish "Text to Shell"

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-cookbooks/pm#101]
Reconsider:

- Name (maybe "Automate Task by...")
- Specific example
- Language around WARNING
- ...

**Comment by deanwampler** [comment]
@adampingel I think I finished this last week, although the name wasn't changed. Anything else needed or should we close this?

**Comment by adampingel** [comment]
Thoughts on the current status & future direction:

- I modified the 20b default to be 8b in the helper function, as my laptop struggles with 20b
- The last two inference calls provide reasonable 1-linerr
- The inclusion of the os in the system prompt is a nice touch
- I'm eager to replace the ollama boilerplate at the top (soon)
- The first query returns a multi-line script.  The response also includes instructions for how to run it, which may be the best thing to ask the user to do with it.  But running a multi-line bash script that we obtain in the previous cell is awkward at best (leading off with `%%bash` might work, but requires modifying the script slightly).

**Comment by adampingel** [comment]
... we might just want to remind the reader that the next lesson offers a programmatic solution.
