### ISSUE TITLE
Fine-tune model

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-cookbooks/pm#104]

**Comment by adampingel** [comment]
cc @Bytes-Explorer

**Comment by Bytes-Explorer** [comment]
@adampingel Can you pls add Shivdeep Singh to this repo? Thanks

**Comment by adampingel** [comment]
@Bytes-Explorer If you send me the github id, I will add it to the org.

**Comment by fayvor** [comment]
This may be a good start for fine-tuning, using InstructLab:
https://developer.ibm.com/tutorials/awb-fine-tune-granite-model-instructlab/

**Comment by fayvor** [comment]
InstructLab will produce a `gguf` file. Once you have that, you can publish to HuggingFace or [run locally in ollama](https://www.markhneedham.com/blog/2023/10/18/ollama-hugging-face-gguf-models/).

**Comment by fayvor** [comment]
I'll do this with Prompt Tuning WatsonX in #122. Putting this one back in the backlog.

**Comment by rawkintrevo** [comment]
pr open: 
https://github.com/ibm-granite-community/granite-code-cookbook/pull/102

Failling in testing bc it can't find a GPU. 

Originally my thought was to come up with some hack to skip over cells, but this on basically would be no running the notebook, so blocked on testing. 

Put a comment on the pr, maybe we need a list of exempt notebooks.
