### ISSUE TITLE
New WatsonX Account and Keys in Repo Secrets

### ISSUE THREAD

**Issue by fayvor** [ibm-granite-cookbooks/pm#128]
- Sign up for a new WatsonX Account with the free ("Lite") plan
- Add WatsonX Machine Learning "Lite" plan
- Create a User API Key
- Add Watson Machine Learning service (Watsonx -> Projects -> Manage -> Services & Integrations  -> Add Service (see https://youtu.be/3sav6vUG_XQ?t=278)
- Create an [Instance API Key](https://cloud.ibm.com/iam/apikeys) and save the key (IBM Cloud > Manage (top bar) > Access(IAM) > Manage identities (left nav) > API keys
- Create a Project and get its project id from the [projects page](https://dataplatform.cloud.ibm.com/projects/?context=wx) > [Select Project] > Manage > General > Details

Add the following env vars to the `utils` and `granite-code-cookbook` repos:
- WATSONX_APIKEY: the api key (_not_ the key id, which starts with ApiKey)
- WATSONX_URL: probably "https://us-south.ml.cloud.ibm.com", the Dallas region
- WATSONX_PROJECT_ID: the project id

**Comment by rawkintrevo** [comment]
i am unable to complete this. I go into my IBM Cloud account search watsonx, click getting started- it takes me to a login page- i try to login and it says i already have an account. Un assigning myself

**Comment by fayvor** [comment]
@rawkintrevo yeah, the product setup and login flow is pretty convoluted. Let's meet tomorrow and walk through it together.

**Comment by adampingel** [comment]
I was able to create the needed values with a new "lite" plan tied to my `apingel@thealliance.ai` address.  I believe these may be lost if unused for 30 days, but given that these will be used in automated tests, that shouldn't be a problem.

**Comment by adampingel** [comment]
Current secretes available in the utils repo:

![image](https://github.com/user-attachments/assets/045dc02b-34a3-4e79-8061-23e631d86a9c)

**Comment by adampingel** [comment]
As just discussed with @fayvor, the WatsonX recipe will be published to the utils repo (and tested there), so we do not plan to distribute these values to other repositories at this time.

**Comment by fayvor** [comment]
I put in a ticket for a recipe to instruct the user how to register on WatsonX, set up a project, and get their api key:
https://github.com/ibm-granite-community/granite-kitchen/issues/47
