### ISSUE TITLE
Move Recipes from Utils to Kitchen

### ISSUE THREAD

**Issue by fayvor** [ibm-granite-cookbooks/pm#138]
- Add the 3 recipes in Components to Kitchen
- Add the 3 recipes in Getting Started to Kitchen
- Add README with ToC links to Kitchen
- In granite-code-cookbook, granite-legal-cookbook, granite-snack-cookbook:
  - Re-point links
  - Re-point pip install
- Delete the 3 recipes in Components from Utils
- Delete the 3 recipes in Getting Started from Utils
- Update README in Utils

**Comment by fayvor** [comment]
Kitchen [PR up here](https://github.com/ibm-granite-community/granite-kitchen/pull/1). -merged

**Comment by fayvor** [comment]
Snack [PR up here](https://github.com/ibm-granite-community/granite-snack-cookbook/pull/2).  -merged

**Comment by fayvor** [comment]
Legal [PR up here](https://github.com/ibm-granite-community/granite-legal-cookbook/pull/6).  -merged

**Comment by fayvor** [comment]
Code [PR up here](https://github.com/ibm-granite-community/granite-code-cookbook/pull/129).  -merged

**Comment by fayvor** [comment]
Kitchen [PR up here](https://github.com/ibm-granite-community/granite-kitchen/pull/5).

@adampingel @rawkintrevo we need to add these API Keys to `granite-kitchen` secrets (can copy over from `utils`) to get Jupyter Notebook tests to pass:
REPLICATE_API_TOKEN
WATSONX_APIKEY
WATSONX_PROJECT_ID
WATSONX_URL

**Comment by fayvor** [comment]
Utils [PR up here](https://github.com/ibm-granite-community/utils/pull/16).  -merged

**Comment by adampingel** [comment]
The above secrets are all now available as org-level secrets to all public repos.

**Comment by fayvor** [comment]
CI is working on Kitchen - [PR merged](https://github.com/ibm-granite-community/granite-kitchen/pull/5).
