### ISSUE TITLE
Update Ollama Hosting Instructions for Clarity

### ISSUE THREAD

**Issue by fayvor** [ibm-granite-cookbooks/pm#139]
@hickeyma has a [PR](https://github.com/ibm-granite-community/utils/pull/14) open against `utils` to update the Ollama setup recipe. Apply these changes instead to the `granite-kitchen` version, as we are migrating the Ollama instructions there.

**Comment by fayvor** [comment]
[PR up here](https://github.com/ibm-granite-community/granite-kitchen/pull/4).

**Comment by rawkintrevo** [comment]
@fayvor #4 is merged. Close this?
