### ISSUE TITLE
Add Pre-Commit Hook to Clear Outputs

### ISSUE THREAD

**Issue by fayvor** [ibm-granite-cookbooks/pm#140]
- Add a pre-commit hook configuration for clearing outputs from committed notebooks in:
  - granite-code-cookbook
  - granite-legal-cookbook
  - granite-snacks-cookbook
  - granite-kitchen
- Document the hook in the community wiki

**Comment by fayvor** [comment]
Code [PR here](https://github.com/ibm-granite-community/granite-code-cookbook/pull/129) (piggyback on #138).  -merged

**Comment by fayvor** [comment]
Legal [PR here](https://github.com/ibm-granite-community/granite-legal-cookbook/pull/6) (piggyback on  #138).  -merged

**Comment by fayvor** [comment]
Snack [PR here](https://github.com/ibm-granite-community/granite-snack-cookbook/pull/2) (piggyback on #138).  -merged

**Comment by fayvor** [comment]
Kitchen [PR here](https://github.com/ibm-granite-community/granite-kitchen/pull/2).  -merged

**Comment by rawkintrevo** [comment]
https://github.com/ibm-granite-community/granite-code-cookbook/pull/129 is blocked bc of our misconfigured git. But ott these are all approved and merged

**Comment by fayvor** [comment]
One TODO left: Document the hook in the community wiki.

**Comment by rawkintrevo** [comment]
sorry you can reopen if you want (or i can if you can't)

**Comment by fayvor** [comment]
Ok, documentation is in the wiki [here](https://github.com/ibm-granite-community/community/wiki/Authoring-Recipes#clear-outputs).
