### ISSUE TITLE
Enable automated testing for snack, legal, and finance cookbooks

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-cookbooks/pm#143]

**Comment by adampingel** [comment]
Please also add granite-kitchen and granite-timeseries-cookbook

**Comment by rawkintrevo** [comment]
✅ Snack https://github.com/ibm-granite-community/granite-snack-cookbook/pull/7

**Comment by rawkintrevo** [comment]
Legal https://github.com/ibm-granite-community/granite-legal-cookbook/pull/8
needs review (error in existing notebook need guidance on how to remediate)

**Comment by rawkintrevo** [comment]
✅  finance https://github.com/ibm-granite-community/granite-finance-cookbook/pull/2

**Comment by rawkintrevo** [comment]
On the kitchen I need more guidance. There's watsonx and ollama junk in here too. Make three workflows?

**Comment by rawkintrevo** [comment]
kitchen https://github.com/ibm-granite-community/granite-kitchen/pull/17

ollama test fails- need @fayvor to review

**Comment by rawkintrevo** [comment]
timeseries https://github.com/ibm-granite-community/granite-timeseries-cookbook/pull/17

**Comment by rawkintrevo** [comment]
Status: 
✅ snacks
🔲 legal - takes 41 minutes, idea to set K at the end for testing, please comment
✅ finance
✅  kitchen - ollama fails, waiting on comment from @fayvor 
✅  timeseries - fails, waiting on @wgifford to update recipes to use open data provider

**Comment by adampingel** [comment]
- Time Series takes 1 hour, but works
- Legal now passes and uses new model
