### ISSUE TITLE
Recipe PR Template with Checklist items

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-cookbooks/pm#144]
Include checklist items from

https://github.com/ibm-granite-community/community/wiki/Authoring-Recipes#checklist

Does this have to be created in every cookbook repo, or is there a way to configure an template for use in any repo in the org?

**Comment by rawkintrevo** [comment]
https://github.com/ibm-granite-community/.github/blob/main/PULL_REQUEST_TEMPLATE.md

**Comment by rawkintrevo** [comment]
view picked up https://github.com/ibm-granite-community/granite-code-cookbook/pull/143
