### ISSUE TITLE
replace kitchen installs with utils installs

### ISSUE THREAD

**Issue by adampingel** [ibm-granite-cookbooks/pm#152]
Replace the pip install granite-kitchen with utils in:

- [x] All `.ipynb` files in all `granite-kitchen`.
- [x] All `.ipynb` files in all `granite-snack-cookbook`.
- [x] All `.ipynb` files in all `granite-timeseries-cookbook`.
- [x] All `.ipynb` files in all `granite-code-cookbook`.
- [x] All `.ipynb` files in all `granite-finance-cookbook`.
- [x] All `.ipynb` files in all `granite-legal-cookbook`.
- [x] https://github.com/ibm-granite-community/community/wiki/Authoring-Recipes#checklist
- [x] PR issue checklist ([edit PR template](https://github.com/ibm-granite-community/.github/blob/main/PULL_REQUEST_TEMPLATE.md))

**Comment by fayvor** [comment]
- [Kitchen PR](https://github.com/ibm-granite-community/granite-kitchen/pull/31).  -merged
- [Snacks PR](https://github.com/ibm-granite-community/granite-snack-cookbook/pull/53)
- Timeseries - noop.
- [Code PR](https://github.com/ibm-granite-community/granite-code-cookbook/pull/146)
- Finance - noop.
- [Legal PR](https://github.com/ibm-granite-community/granite-legal-cookbook/pull/17)
- [.github PR](https://github.com/ibm-granite-community/.github/pull/3) (for the PR checklist)

**Comment by adampingel** [comment]
merged the kitchen changes

**Comment by adampingel** [comment]
everything is approved and merged.  Nice!
