### ISSUE TITLE
Test each notebook with a new Virtual Env

### ISSUE THREAD

**Issue by fayvor** [ibm-granite-cookbooks/pm#156]
Modify CI workflow in these cookbooks:
- [ ] Kitchen
- [ ] Snack
- [ ] Code
- [ ] Legal
- [ ] Timeseries
- [ ] Finance

Also: strip the Python version from the notebook?

**Comment by fayvor** [comment]
[Kitchen PR](https://github.com/ibm-granite-community/granite-kitchen/pull/32)
[Snacks PR](https://github.com/ibm-granite-community/granite-snack-cookbook/pull/61)
[Code PR](https://github.com/ibm-granite-community/granite-code-cookbook/pull/148)
[Legal PR](https://github.com/ibm-granite-community/granite-legal-cookbook/pull/18)
[Timeseries PR](https://github.com/ibm-granite-community/granite-timeseries-cookbook/pull/23)
[Finance PR](https://github.com/ibm-granite-community/granite-finance-cookbook/pull/4)

All Merged.

**Comment by adampingel** [comment]
From the comments on the PRs:

@deanwampler suggests doing this comment filtering consistently:

```
notebooks=$(cat .github/notebook_lists/vanilla_notebooks.txt | grep -v '^#' | tr '\n' ' ')
```

@rawkintrevo suggests weighing the pros and cons of 1 workflow per notebook.

Let's file an issue for the former and discuss the latter before we close this ticket.  Both otherwise I will merge the PRs.

**Comment by bjhargrave** [comment]
I can help with GitHub Actions workflows. I have a bunch of experience. I would recommend one job per notebook using a matrix so they share a single workflow.

See https://github.com/instructlab/instructlab/blob/4780b8dc6e284d95c5af2b3fd120a9deffeb5fc2/.github/workflows/lint.yml#L43-L97 for one I did.

**Comment by deanwampler** [comment]
> From the comments on the PRs:
> 
> @deanwampler suggests doing this comment filtering consistently:
> 
> ```
> notebooks=$(cat .github/notebook_lists/vanilla_notebooks.txt | grep -v '^#' | tr '\n' ' ')
> ```
> 
> @rawkintrevo suggests weighing the pros and cons of 1 workflow per notebook.
> 
> Let's file an issue for the former and discuss the latter before we close this ticket. Both otherwise I will merge the PRs.

I created https://github.com/ibm-granite-community/pm/issues/157 to add the `| grep -v '^#'` and also `set -e`. Most of the repos already have PRs. I'll create PRs for the remaining two cited in the issue later today.

**Comment by rawkintrevo** [comment]
I agree with @bjhargrave . I remember the matrices from travis, i didn't know how to do it in ghactions. @bjhargrave can you join the standup tomorrow to guide @adampingel and @fayvor ?

**Comment by bjhargrave** [comment]
> can you join the standup tomorrow

Sure, I will need to added to the invite.

**Comment by fayvor** [comment]
The benefit I see of using a matrix would be to [parallelize the test runs](https://www.testmo.com/guides/github-actions-parallel-testing/). If we go the direction of one workflow per notebook, we should try and get the workflows running in parallel.
