### ISSUE TITLE
Community Code of Conduct

### ISSUE THREAD

**Issue by AnthonyJAnnunziata** [ibm-granite-cookbooks/pm#94]
We need to add a community code of conduct. Should be straightforward and borrowing heavily from generally accepted CoC such as: https://ai-alliance.cdn.prismic.io/ai-alliance/Zl-MG5m069VX1dgH_AIAllianceCodeofConduct.pdf

**Comment by adampingel** [comment]
@deanwampler Created a community of conduct document in a dedicated `community` repo: https://github.com/ibm-granite-community/community.  If we're changing that, please keep that other version in sync or update any references to it.

**Comment by deanwampler** [comment]
In [PR #37](https://github.com/ibm-granite-community/granite-code-cookbook/pull/37), I added a reference to the community CoC. I'll close this once it's merged.

**Comment by deanwampler** [comment]
The PR is merged, so closing this issue.
