### ISSUE TITLE
Replicate: delete model ibm-granite/granite-8b-code-base-128k

### ISSUE THREAD

**Issue by jolson-ibm** [ibm-granite-cookbooks/pm#97]
Need to delete model ibm-granite/granite-8b-code-base-128k. Unable to do so using the Replicate UI, as this is a versioned model.

**Comment by jolson-ibm** [comment]
Have informed Replicate support via the Slack channel that I'd like this model deleted, but cannot delete it using the Replicate UI. Will update this ticket when they get back to me.

**Comment by rawkintrevo** [comment]
In the meantime- can it be renamed to something like `[deprecated] granite-8b-code-base-128k` ?

**Comment by jolson-ibm** [comment]
Done. You have to delete the deployment, each version, etc and then finally you can delete the model itself.

I'll close this ticket
